### PR TITLE
Fix PlotDocs Module

### PR DESCRIPTION
**Pull request by daschw**
This fixes the PlotDocs module and runs the exported functions in `docs/make.jl`.
Furthermore the backend example images for GR, PyPlot and PlotlyJS as well as most of the general documentation images are moved to PlotReferenceImages.
The docs are built and deployed using the default Documenter html theme:
plotdocs
If you prefer the old mkdocs build @mkborregaard, I can revert this change.
This does not really fix the synchronisation issue with Plots, but I hope it's a step in the right direction and it makes it easier to update the images in the docs.

This requires https://github.com/JuliaPlots/Plots.jl/pull/1730 and https://github.com/JuliaPlots/PlotReferenceImages.jl/pull/31

### CODE REVIEW

**Comment by mkborregaard** [comment]
Great. Why the theme change?

**Comment by daschw** [comment]
Mainly because it's the "default julia package documentation theme" and I wanted to try it during the process of working on this PR. I don't really have a strong preference, so I kept it for now. We can still switch back, however, if you'd prefer that

**Comment by daschw** [comment]
Is there any reason not to integrate the documentation into Plots.jl, once all documentaion images are ported to PlotReferenceImages? Then the docs would update automatically with every Plots build.

**Comment by daschw** [comment]
What's your opinion on the theme? Should I revert?

**Comment by mkborregaard** [comment]
I don't care that much actually. I like the existing one because the default theme is soooo boring.

**Comment by daschw** [comment]
I switched back to the old Plots theme now, but left the lines for the documenter theme build as comments, if we should change our mind in the future.

**Comment by daschw** [comment]
Why did the docs not build, when I merged this PR?
It seems like the last build was on September 14 (https://github.com/JuliaPlots/PlotDocs.jl/tree/gh-pages) but there have been at least 2 merged PRs since then.
Shouldn't the docs build automatically with each merge?

**Comment by mkborregaard** [comment]
Yes they should, but only when the build does not fail on Travis. Have the changes built now you've merged #110?

**Comment by mkborregaard** [comment]
Yes they should, but only when the build does not fail on Travis. Have the changes built now you've merged #110?

**Comment by mkborregaard** [comment]
Yes they should, but only when the build does not fail on Travis. Have the changes built now you've merged #110?

**Comment by mkborregaard** [comment]
Yes they should, but only when the build does not fail on Travis. But see #111

**Pull request merged**
