### PR TITLE
transition `pyplot` -> `pythonplot`

### PR DESCRIPTION
**Pull request by t-bltg**
Following https://github.com/JuliaPlots/Plots.jl/pull/4542.

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
The docs for Plots.jl aren't updated [automatically].

**Comment by t-bltg** [comment]
What do you mean ?

**Comment by PallHaraldsson** [comment]
I noticed you changing e.g. backends.md and in README "Documentation for Plots.jl" but at https://docs.juliaplots.org/stable/backends/ I still see PyPlot. Maybe I misunderstand something, but I think it should be updated at least eventually. I'm not sure there's anything to do it automatically.

**Comment by t-bltg** [comment]
It's because the docs are at `https://docs.juliaplots.org/dev/backends` for `Plots#master`.

The `stable` docs at https://docs.juliaplots.org/stable are built when a new version of `Plots` is released.

**Comment by PallHaraldsson** [comment]
Yes, realized that now (and this rather recent), I guess a new version will be released soon for Plots.jl, and needed, then this changes automatically.

**Comment by t-bltg** [comment]
404 fixed in https://github.com/JuliaPlots/PlotDocs.jl/pull/331.

**Pull request merged**
