### PR TITLE
Allow PR preview builds of docs

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by daschw** [comment]
Nice!

**Comment by asinghvi17** [comment]
tjuliaplots.org/previews/PR176/index.html should have the preview up.

**Comment by daschw** [comment]
I get a 404.

**Comment by mkborregaard** [comment]
It's https://docs.juliaplots.org/previews/PR176/index.html
there was a typo

**Comment by daschw** [comment]
Ah, nice.

**Pull request merged**
