### PR TITLE
Add documentation for GraphRecipes

### PR DESCRIPTION
**Pull request by JackDevine**
I finally kicked the procrastination monster and did this.

## Summary
* Slight restructure of the ecosystem bit, GraphRecipes has its own page separate from all of the other ecosystem examples
* PlotRecipes entry in the ecosystem is deleted, which makes sense, since it is now defunct
* Added examples from GraphRecipes readme as well as an explanation of all of the keyword arguments

Part of https://github.com/JuliaPlots/GraphRecipes.jl/issues/59

### CODE REVIEW

**Comment by mkborregaard** [comment]
Awesome :heart:

**Comment by JackDevine** [comment]
I don't understand the CI failure, it seems to have something to do with PGFPlots.

I didn't add any tests with this PR, all of the tests happen on the GraphRecipes repo.

**Comment by mkborregaard** [comment]
Yes it's unrelated

**Comment by JackDevine** [comment]
Right now my preference is to keep all of the tests in the GraphRecipes repo and just have images copied over to this repo. If that becomes too annoying from a maintenance perspective, then I will consider moving some tests over here.

I will hold off merging right now to give people some time to review if they feel necessary.

**Comment by mkborregaard** [comment]
I agree with keeping the tests in GraphRecipes

**Comment by daschw** [comment]
The tests failed with Plots 0.29.1, but should work with Plots 0.29.2 (https://github.com/JuliaPlots/Plots.jl/pull/2398)

**Comment by daschw** [comment]
I restarted the build.

**Pull request merged**
