### PR TITLE
Add ColorSchemes documentation

### PR DESCRIPTION
**Pull request by daschw**

### CODE REVIEW

**Comment by daschw** [comment]
Weird, I can't reproduce the [travis error](https://travis-ci.org/github/JuliaPlots/PlotDocs.jl/builds/679654273#L1614) on my system. Any ideas @BeastyBlacksmith ? Could it be different versions of texlive? I have 2019, travis uses 2015.

**Comment by daschw** [comment]
https://github.com/live-clones/pgfplots/blob/master/doc/latex/pgfplots/ChangeLog#L116
I think texlive 2016 is required for the new ColorSchemes implementation in Plots with nonuniform colormaps for pgfplotsx.
How should we communicate this requirement? Is it bad to have this requirement?

**Comment by mkborregaard** [comment]
Nice! I guess we might also update https://juliagraphics.github.io/ColorSchemes.jl/stable/plotting/#Plots.jl-1

**Comment by BeastyBlacksmith** [comment]
I think that is reasonable, but stating compatibility requirements in LaTeX is hard.
We should state it in the docs and long term solution might be shipping TeXLive_pgfplots_jll, but I am not entirely sure if that would work out

**Pull request merged**
