### PR TITLE
Add note on JuliaFormatter

### PR DESCRIPTION
**Pull request by t-bltg**

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
Doesn't this fit into contributing? And I thought we have an action that formats PRs automatically, no?

**Comment by t-bltg** [comment]
> Doesn't this fit into contributing?

Moved to `contributing.md`, which I shamefully never read :laughing:.

> And I thought we have an action that formats PRs automatically, no?

I couldn't find a way to do that :confused:.
It currently only checks that the code is formatted, and [errors](https://github.com/JuliaPlots/Plots.jl/blob/214663aa4bf3d0e383fe5ab7babf0acccb81715f/.github/workflows/format.yml#L26) the CI if not.

**Comment by BeastyBlacksmith** [comment]
Hmm... there is https://github.com/julia-actions/julia-format/blob/master/workflows/format_pr.yml, which would at least run it on intervals

**Comment by BeastyBlacksmith** [comment]
> Moved to contributing.md, which I shamefully never read 😆.

Yeah, we should update that section and put a badge on the Plots README

**Comment by t-bltg** [comment]
> Yeah, we should update that section and put a badge on the Plots README

I'm not familiar with badges :roll_eyes: 

> Hmm... there is https://github.com/julia-actions/julia-format/blob/master/workflows/format_pr.yml, which would at least run it on intervals

Don't you think it might add constant noise if we get automated formatting PRs in addition to precompile PRs ?

**Comment by t-bltg** [comment]
Or yes, maybe [cron scheduled PRs](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events) is acceptable.

**Comment by BeastyBlacksmith** [comment]
Yeah should be fine

**Comment by BeastyBlacksmith** [comment]
> I'm not familiar with badges 🙄

I'd do the badge if you proofread that section ;)

**Pull request closed without merging**
