### PR TITLE
Add icon for browser tabs (favicon)

### LINKED ISSUE #204: Missing icon in browser tabs (favicon)
The icon for tabs is missing. I believe it is because of the missing asset `favicon`

image

### PR DESCRIPTION
**Pull request by LakshyaKhatri**
Fixes #204 

Preview:
Screenshot from 2020-06-24 19-11-37

### CODE REVIEW

**Comment by daschw** [comment]
Thanks!

**Comment by isentropic** [comment]
@LakshyaKhatri Would you please go extra step and make the icon have white background? So, change the background of the logo from transparent to white?

**Comment by LakshyaKhatri** [comment]
Okay!

**Comment by LakshyaKhatri** [comment]
The PR has been closed though. if you could open it back I will push the changes :smile: 
or I will just open another PR.

**Comment by LakshyaKhatri** [comment]
here we go: https://github.com/JuliaPlots/PlotDocs.jl/pull/206

**Pull request merged**
