### PR TITLE
Revert "fix table urls on attributes page"

### PR DESCRIPTION
**Pull request by daschw**
Reverts JuliaPlots/PlotDocs.jl#101

### CODE REVIEW

**Comment by mkborregaard** [comment]
did it not work?

**Comment by daschw** [comment]
No, I don't know how to change the urls for this to work.

**Comment by daschw** [comment]
But this would be very important for our docs.

**Comment by mkborregaard** [comment]
I think this might be a Documenter issue - if you look at the generated html (in the gh-pages branch of PlotDocs) you'll see that it's changed the link to `src="../supported*types.html"` instead of `src="../supported_types.html"`

**Comment by mkborregaard** [comment]
https://github.com/JuliaDocs/Documenter.jl/issues/820

**Comment by mkborregaard** [comment]
Fixed in https://github.com/JuliaPlots/PlotDocs.jl/pull/103

**Pull request merged**
