### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[ci skip]

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
Thanks :+1:

**Comment by PallHaraldsson** [comment]
That was quick!

I was going to mention/ask about something else. I wasn't sure what the default backend was so I went looking there.

Anyway, I ended up looking at the code, and for other issues, if/how to improve startup:

```
using FFMPEG

@reexport using RecipesBase
import RecipesBase: plot, plot!, animate, is_explicit
using Base.Meta
@reexport using PlotUtils
@reexport using PlotThemes
import Showoff
import StatsBase
import JSON

[..]

import Measures
module PlotMeasures
import Measures
import Measures: Length, AbsoluteLength, Measure, BoundingBox, mm, cm, inch, pt, width, height, w, h
```

I can cut off 0.73 sec of just this one (but I'm not sure it's needed at all, most of the time):

```
julia> @time using FFMPEG
  1.737923 seconds (1.45 M allocations: 85.451 MiB, 0.46% gc time)
```

The other bit isn't I think slow, but looks odd to me.

**Comment by BeastyBlacksmith** [comment]
It is not really clear to me what the question is, but FFMPEG is used to create animations.

**Comment by PallHaraldsson** [comment]
Ok, I just knew about it to play, or I guess record (compressed) video, I just doubt it's very common to do?

I could make the startup faster of FFMPEG  (and I think it would apply, not slow down later), with the lower opt. trick.

Still, itsn't this a good candidate for the "optional requires feature" (that I've never tried out)? https://github.com/JuliaPackaging/Requires.jl

**Comment by BeastyBlacksmith** [comment]
That would require users to add FFMPEG separately, which is an option that would need to be discussed in an issue on the Plots repo.

**Comment by PallHaraldsson** [comment]
Ok, this must be a common enough experience, but I ask anyway.

Can't we postpone `using` a package indefinitely, here FFMPEG, until it's actually used? If you're worried about getting errors (we shouldn't), and since it's already in Projects.toml file, we culd still rely on the `using` not giving an error (at least for the reason it's not installed).

**Comment by BeastyBlacksmith** [comment]
That is what Requires is for. I would suggest to open an issue for this and see what other people think about this. I am rather neutral.

**Comment by PallHaraldsson** [comment]
Ok, maybe I misunderstood requires, or you do, as you say "would require users to add FFMPEG separately", but what I have in mind wouldn't.

You see I made a PR, which was closed (as wrong place), but should have worked, and the good thing is should for all JLL packages is I get it merged at the right place.

**Pull request merged**
