### PR TITLE
add pgfplotsx-examples

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**

### CODE REVIEW

**Comment by daschw** [comment]
Nice

**Comment by daschw** [comment]
It seems like pdftocairo is provided by the package poppler-utils in ubuntu. https://www.google.com/url?q=http://manpages.ubuntu.com/manpages/trusty/man1/pdftocairo.1.html&sa=U&ved=2ahUKEwiDh6if25boAhVR2KQKHce_AbgQFjAAegQIAxAB&usg=AOvVaw3okdhr5SfGcxJKHaExT2FA

**Comment by BeastyBlacksmith** [comment]
You know, I love CI.
    .... once it works >.<

**Comment by daschw** [comment]
Not sure how to fix the current luatex error ...

**Comment by BeastyBlacksmith** [comment]
https://github.com/JuliaPlots/Plots.jl/pull/2454

**Comment by BeastyBlacksmith** [comment]
I think it is working now 🤞

**Comment by daschw** [comment]
Simon 1 : 0 Travis :wink:

**Pull request merged**
