### PR TITLE
Fix 404 errors

### PR DESCRIPTION
**Pull request by tshort**
I think these link addresses are wrong. Note that I didn't test these.

### CODE REVIEW

**Comment by mkborregaard** [comment]
I'm not sure that's it, as they were working a few days ago - @daschw ?

**Comment by daschw** [comment]
I also tried to fix it that way and tested it locally but it does not seem to work. Nevertheless, the links were changed by me when I tried the default documenter theme one or two months ago. Before they were as in @tshort 's implementation here and I'm not sure, we've had a successful build since then. So maybe there's just something wrong with my local test build.
I'll give it a shot.

**Comment by daschw** [comment]
:tada: Yay, it worked. Thanks a lot @tshort!

**Comment by mkborregaard** [comment]
Sorry for the noise!

**Pull request merged**
