### PR TITLE
Autogen unicodeplots and inspectdr

### PR DESCRIPTION
**Pull request by t-bltg**
Should replace [inspectdr.md](https://github.com/JuliaPlots/PlotDocs.jl/blob/master/docs/src/examples/inspectdr.md) and [unicodeplots.md](https://github.com/JuliaPlots/PlotDocs.jl/blob/master/docs/src/examples/unicodeplots.md).

Unicodeplots
------
unicode-sample

InspectDR
------
inspectdr-sample

### CODE REVIEW

**Comment by t-bltg** [comment]
I've added two example from my local build of hmtl files.

I think that `UnicodePlots` really looks good, but we have to wait for a new release of `Documenter.jl` since I used https://github.com/JuliaDocs/Documenter.jl/pull/1441.

However, I have a font issues with `InspectDR`, @BeastyBlacksmith do you have any clue of what is causing this ?

**Comment by BeastyBlacksmith** [comment]
@ma-laforge might know

**Comment by ma-laforge** [comment]
Hi. I think I'm not running with the right configuration: Can't reproduce your results. In the results below, I used the following config:
```
OS: Ubuntu 18.04
Julia: v1.6.1
Cairo: v1.0.5
Gtk: v1.1.8
Pango_jll = "1.42.4+10" (Font engine, I believe)
Plots: v1.18.2
```

### My results
```
Plot: Plots._examples[4]
```
image

### Comments
 - I don't get the strange tick labels you show in your screenshot.
 - My legend does not try to display "ys" at all. It displays "line" - which is the same labels I see in the GR output.
 - I am not 100% certain the InspectDR backend reads in the data correctly when the user provides data in matrices or labels as vectors (to match the structure when y is in matrix format).
 - I use GR and PyPlot as models, and try to replicate their behaviour as much as possible.

### Your setup
Can you please explain what you did to obtain these results @t-bltg ?

For example, are you on mac-os? I've only really verified functionality on Windows and Linux.

**Comment by t-bltg** [comment]
@ma-laforge thanks your detailed answer.
I'm on `Linux` too, `Ubuntu 20.04`.

I get the same output when issuing  `$ julia -e 'using Plots; test_examples(:inspectdr, 4); png("ex4")'`:
ex4
, so we're on the same page here.

The issue arises when I use `Documenter` to generate the `PlotDocs` html pages. Here is the procedure:
```bash
] dev https://github.com/JuliaPlots/PlotDocs.jl
] dev https://github.com/JuliaDocs/Documenter.jl
$ cd ~/.julia/dev/PlotDocs
$ wget github.com/JuliaPlots/PlotDocs.jl/pull/246.patch -O - | patch -p1
$ julia --project=docs/ docs/make.jl
```
20min later, I get the generated documentation in ~/.julia/dev/PlotDocs/build`.

The issue comes from the `svg` integration in the `html` files:
```html
<h3 id="inspectdr-ref4"><a class="docs-heading-anchor" href="#inspectdr-ref4">Colors</a><a id="inspectdr-ref4-1"></a><a class="docs-heading-anchor-permalink" href="#inspectdr-ref4" title="Permalink"></a></h3><p>Access predefined palettes (or build your own with the <code>colorscheme</code> method). Line/marker colors are auto-generated from the plot&#39;s palette, unless overridden.  Set the <code>z</code> argument to turn on series gradients.</p><pre><code class="language-julia">y = rand(100)
plot(0:10:100, rand(11, 4), lab = &quot;lines&quot;, w = 3, palette = cgrad(:grays), fill = 0, α = 0.6)
scatter!(y, zcolor = abs.(y .- 0.5), m = (:heat, 0.8, Plots.stroke(1, :green)), ms = 10 * abs.(y .- 0.5) .+ 4, lab = &quot;grad&quot;)</code></pre><?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="600pt" height="400pt" viewBox="0 0 600 400" version="1.1">
<defs>
<g>
<symbol overflow="visible" id="glyph0-0">
<path style="stroke:none;" d="M 0.59375 2.125 L 0.59375 -8.46875 L 6.59375 -8.46875 L 6.59375 2.125 Z M 1.265625 1.453125 L 5.9375 1.453125 L 5.9375 -7.78125 L 1.265625 -7.78125 Z M 1.265625 1.453125 "/>
</symbol>
<symbol overflow="visible" id="glyph0-1">
<path style="stroke:none;" d="M 3.8125 -7.96875 C 3.207031 -7.96875 2.75 -7.664062 2.4375 -7.0625 C 2.132812 -6.46875 1.984375 -5.566406 1.984375 -4.359375 C 1.984375 -3.160156 2.132812 -2.257812 2.4375 -1.65625 C 2.75 -1.0625 3.207031 -0.765625 3.8125 -0.765625 C 4.425781 -0.765625 4.882812 -1.0625 5.1875 -1.65625 C 5.5 -2.257812 5.65625 -3.160156 5.65625 -4.359375 C 5.65625 -5.566406 5.5 -6.46875 5.1875 -7.0625 C 4.882812 -7.664062 4.425781 -7.96875 3.8125 -7.96875 Z M 3.8125 -8.90625 C 4.789062 -8.90625 5.539062 -8.515625 6.0625 -7.734375 C 6.582031 -6.960938 6.84375 -5.835938 6.84375 -4.359375 C 6.84375 -2.890625 6.582031 -1.765625 6.0625 -0.984375 C 5.539062 -0.210938 4.789062 0.171875 3.8125 0.171875 C 2.832031 0.171875 2.082031 -0.210938 1.5625 -0.984375 C 1.050781 -1.765625 0.796875 -2.890625 0.796875 -4.359375 C 0.796875 -5.835938 1.050781 -6.960938 1.5625 -7.734375 C 2.082031 -8.515625 2.832031 -8.90625 3.8125 -8.90625 Z M 3.8125 -8.90625 "/>
</symbol>
[...]
```

**Comment by t-bltg** [comment]
All good now with png output (don't bother the warning, it will be suppressed)  :tada:
ex4-ok

**Comment by ma-laforge** [comment]
Great to hear. Thanks for helping to improve documentation @t-bltg.

**Comment by BeastyBlacksmith** [comment]
Thanks a lot

**Comment by t-bltg** [comment]
@BeastyBlacksmith, I hope that merging this now won't break building docs, since `v0.27.4` of `Documenter.jl` is not yet released (https://github.com/JuliaPlots/PlotDocs.jl/pull/246#issuecomment-877508670).

**Comment by t-bltg** [comment]
This is now live:
- https://docs.juliaplots.org/latest/generated/inspectdr
- https://docs.juliaplots.org/latest/generated/unicodeplots

**Pull request merged**
