### PR TITLE
Updated waves animation example to incorporate camera pan & progress meter

### PR DESCRIPTION
**Pull request by ianshmean**
Discussed in https://github.com/JuliaPlots/Plots.jl/issues/1273

### CODE REVIEW

**Comment by ianshmean** [comment]
Done, sorry, committed it but missed it on the PR 

#67

**Comment by mkborregaard** [comment]
Great - you don't have to open a new PR though, you can just keep pushing to this one. Would you mind doing that? it'll give the cleanest history.

**Comment by ianshmean** [comment]
Of course. Done. (bumbling my way around here..)

**Comment by mkborregaard** [comment]
Awesome, thanks a lot!

**Pull request merged**
