### PR TITLE
axis logo

### PR DESCRIPTION
**Pull request by isentropic**
The axis logo from https://github.com/JuliaPlots/Plots.jl/issues/2510

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
@isentropic you are okayw with us using this for the JuliaPlots organization instead of Plots.jl?

**Comment by isentropic** [comment]
@BeastyBlacksmith I'm totally fine with all of your decisions

**Comment by mkborregaard** [comment]
I just merged this but neither the png nor the svg works (or at least they can't be opened on my computer)

**Comment by isentropic** [comment]
> 
> 
> I just merged this but neither the png nor the svg works (or at least they can't be opened on my computer)

That's very odd. I'll reupload tomorrow once I get to work

**Comment by isentropic** [comment]
> 
> 
> I just merged this but neither the png nor the svg works (or at least they can't be opened on my computer)

Hmmm, I think its on your end, I opened both svg and png by using web github viewing

**Comment by BeastyBlacksmith** [comment]
all good, you can see the result [here](https://github.com/JuliaPlots)

**Pull request merged**
