### PR TITLE
Addition to PyPlot examples

### PR DESCRIPTION
**Pull request by mcawte**
The layout example has been changed from using commas to semi colons in line with the examples in the advanced layout .md, and an example has been given to show how to create animations with subplots.

### CODE REVIEW

**Comment by mkborregaard** [comment]
Ah. Sorry, the example markdown files are created automatically by this function: https://github.com/JuliaPlots/PlotDocs.jl/blob/master/src/PlotDocs.jl#L45-L104 , using the code here: https://github.com/JuliaPlots/Plots.jl/blob/master/src/examples.jl

So if you want to modify the examples you should make a PR on that file in Plots instead. Sorry, didn't realize you were modifying examples.

**Comment by mcawte** [comment]
No worries. I have forked and cloned the examples.jl file now, but I can see under the subplots section this code: 

PlotExample("Subplots",
    """
    Use the `layout` keyword, and optionally the convenient `@layout` macro to generate arbitrarily complex subplot layouts.
    """,
    [:(begin
        l = @layout([a{0.1h}; b [c;d e]])
        plot(randn(100,5), layout=l, t=[:line :histogram :scatter :steppre :bar], leg=false, ticks=nothing, border=false)
    end)]
),

That already has the fix from commas to semi colons in the layout array, but when looking at the documentation website at https://juliaplots.github.io/examples/pyplot/ , the code that is on display is:

l = @layout([a{0.1h},b [c,d e]])
plot(randn(100,5),layout=l,t=[:line :histogram :scatter :steppre :bar],leg=false,ticks=nothing,border=false)

Which is not correct. Is that because the current examples.jl file has not been built so the website has not been updated, or does the website build from somewhere else?

**Comment by mkborregaard** [comment]
Interesting, I don't know when @tbreloff last rebuilt the docs.

**Comment by mkborregaard** [comment]
I see nobody has revisited the PRs here for a while - I assume it was OK to close this?

**Pull request closed without merging**
