### PR TITLE
Revert "Change favicon background to white"

### PR DESCRIPTION
**Pull request by isentropic**
Perhaps you want add the rounded corners. I mistakenly merged the previous one

### CODE REVIEW

**Comment by isentropic** [comment]
> Perhaps you want add the rounded corners. I mistakenly merged the previous one

@LakshyaKhatri

**Comment by LakshyaKhatri** [comment]
Yes, I am pushing the rounded one.

**Comment by LakshyaKhatri** [comment]
I have to open a PR to this branch since I can't push the changes directly to this one.

**Comment by isentropic** [comment]
Should I merge this now?

**Comment by LakshyaKhatri** [comment]
You have to merge this one too: https://github.com/JuliaPlots/PlotDocs.jl/pull/208, to reflect the changes.

**Comment by LakshyaKhatri** [comment]
I don't know why we are doing that much hassle! :sweat_smile:

**Comment by isentropic** [comment]
Yeah sorry for this, I accidentally reverted the last PR. So merging the  #208 is all I have to do? 

If this were just code, i couldve seen the changes easily and done this without any hassle :)

**Comment by LakshyaKhatri** [comment]
Now you have to merge both #207 and #208 (since #208 is a PR to revert-206-lakshya/favicon branch rather than the master branch).

**Pull request merged**
