### PR TITLE
[WIP] Add overview of colorschemes to docs

### PR DESCRIPTION
**Pull request by SaschaMann**
Following my recent question on Gitter, this adds an overview of available colorschemes to the docs. It mostly copies the content of [this discourse post](https://discourse.julialang.org/t/current-list-of-colorschemes-in-plots-jl/5420/2?u=mkborregaard).

I am not entirely sure about the proper section, whether this belongs in examples or Colors. Imo Colors would be the right place because the colours shouldn't really differ between backends.

Is there a way to autogenerate these png's for md-files outside of `examples` instead of hardcoding them to avoid having to manually upgrade them in the future?

### CODE REVIEW

**Comment by mkborregaard** [comment]
Great, thanks! I've wanted to do this for some time. There's more information in the discourse post, e.g. about how to change/set the color library and how it's actually not necessary unless there are namespace clashes, which I think should def also be here. And also on how you can reverse the scheme with "_r". 
In addition many of them are on licences that require attribution in the docs, those can be found in the source files (in PlotUtils ). Would you mind adding this?
Currently all plots in the images are hardcoded, this should change of course but we haven't agreed on how yet. @ChrisRackauckas only ported our docs to Documenter this weekend :-)

**Comment by SaschaMann** [comment]
I've added the other info from the post that you mentioned.

I tried to give a short info on the license and then link to LICENSE.md, otherwise the page would be cluttered with legal text. Is that enough or should I add the full texts to the page?

**Comment by mkborregaard** [comment]
That's perfect, thanks. Could you make the titles smaller on the misc library, so they don't overlap? Other than that this is good to merge IMO.

**Comment by SaschaMann** [comment]
I've created them using `showlibrary`, perhaps that recipe should be changed as well to avoid the overlap?

Anyway, rescaling it to 0.75 font size fixes this.

**Comment by mkborregaard** [comment]
Yeah, that's a good idea. Oh, given this https://discourse.julialang.org/t/setting-the-color-scale-in-plots/6373/5 , could you mention `clims`?

**Comment by mkborregaard** [comment]
Promise, that's my last request :-)

**Comment by SaschaMann** [comment]
I'm not sure I understand what `clims` does.

Does it limit the schemes, so that for example rainbow would only go from green to orange, or does it set which data-value is associated with which colour, e.g. clims of `[0.0, 0.9]` would mean that values >0.9 are all red (using rainbow)?

**Comment by mkborregaard** [comment]
It defines the values that correspond to the ends of the color schemes:
```julia
a = randn(10,10);
gr(c = :RdBu, size = (800, 400))
plot(heatmap(a), heatmap(a, clims = (-5,5)))
```
skaermbillede 2017-10-10 kl 15 10 01

**Comment by SaschaMann** [comment]
Okay, thanks. I will add info about that.

**Comment by mkborregaard** [comment]
Cool. I dont think there's a functionality for subsetting gradients, but it could be implemented as
```julia
subsetgrad(grad, lims) = cgrad([getindex.(cgrad(grad), lims)...])
```
then
```
heatmap(a, color = subsetgrad(:rainbow, (0.7, 0.9))
```

**Comment by mkborregaard** [comment]
Nice - ready to merge?

**Comment by SaschaMann** [comment]
👍

**Comment by mkborregaard** [comment]
Thanks!

**Pull request merged**
