### PR TITLE
Maybe fix redirects in netlify

### PR DESCRIPTION
**Pull request by fonsp**
I'm not good with grep and sed so I hope I did this correctly

This PR uses the `*` and `:splat` features to redirect all subpaths, not just the path itself:

https://docs.netlify.com/routing/redirects/redirect-options/#splats

### CODE REVIEW

**Comment by fonsp** [comment]
Seems to work now!

Only thing left is: redirect `/v1.38` to `/v1.38/`, `/latest` to `/latest/`, etc. (Because the version selector in the bottom right send you to `/v1.38` instead of `/v1.38/`.)

Right now we have

```toml
[[redirects]]
  from = "/v1.30/*"
  to = "/v1.30.2/:splat"
  status = 200
  force = true
```

you could add a second rule:

```toml
[[redirects]]
  from = "/v1.30/*"
  to = "/v1.30.2/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/v1.30"
  to = "/v1.30/"
```

**Comment by BeastyBlacksmith** [comment]
Thanks! Do you happen to know what counts for the Bandwith limit? Is that the traffic of the viewers?

**Comment by BeastyBlacksmith** [comment]
> you could add a second rule:

Thats not working.

https://docs.netlify.com/routing/redirects/redirect-options/#trailing-slash

**Comment by fonsp** [comment]
Ah sorry, missed that part. Did you enable the "Pretty URLs" feature already?

**Comment by fonsp** [comment]
Bandwidth limit is about outbound data transfer to site visitors. If bandwidth ever becomes an issue, you could apply for https://www.netlify.com/legal/open-source-policy/ (worked for Pluto).

**Comment by BeastyBlacksmith** [comment]
> Ah sorry, missed that part. Did you enable the "Pretty URLs" feature already?

Yes

**Comment by BeastyBlacksmith** [comment]
I'll merge this as is and hope for https://github.com/JuliaDocs/Documenter.jl/pull/2023 to get merged

**Pull request merged**
