### PR TITLE
Fix grouping error on `violin`, `boxplot`

### PR DESCRIPTION
**Pull request by nilshg**
It seems that the way grouping has to be specified has changed since this was written, see https://discourse.julialang.org/t/problem-creating-violin-plots/41298/7

### CODE REVIEW

**Comment by mkborregaard** [comment]
Hmm wouldn't it be better to again allow the old behaviour?

**Comment by nilshg** [comment]
That's above my pay grade I suppose :)

I tried to look through https://github.com/JuliaPlots/StatsPlots.jl/commits/fbbe891de4c50ddc833374ce82b064ff5eb40bfb/src/violin.jl to see where this change was introduced, but couldn't really work it out, so the behaviour might have changed inadvertently?

**Comment by mkborregaard** [comment]
Screenshot 2020-11-28 at 12 01 42

Yes I think it might have been inadvertant :-)

**Comment by BeastyBlacksmith** [comment]
I am closing this since I can't reproduce the issue on StatsPlots 0.14.21

**Pull request closed without merging**
