### PR TITLE
Change tables of supported attrs to HTML

### PR DESCRIPTION
**Pull request by SaschaMann**
The [Supported Attributes](https://docs.juliaplots.org/latest/supported/) page currently has tables in png format, which e.g. can't be searched. This changes it to HTML tables like on the [Attributes](http://docs.juliaplots.org/latest/attributes/) page.

---

Right now, it uses `R` for series types supported through series recipes and `N` for natively supported types. This is not very readable. Any ideas what would be better? Perhaps something like ✔️  for native support, 📃 for recipe support and ❌ for no support?

### CODE REVIEW

**Comment by mkborregaard** [comment]
Nice. I think those three icons might look too crowded, perhaps something simpler?

**Comment by mkborregaard** [comment]
This was just opened lol https://github.com/JuliaPlots/Plots.jl/issues/1387

**Comment by crstnbr** [comment]
Timing :) Thanks for changing this!

**Comment by SaschaMann** [comment]
This is what it looks like right now:

grafik

I guess the old style with completely coloured cells would work best but I don't know how to do that in the CSS/HTML part.

**Comment by mkborregaard** [comment]
Pretty but definitely not as easy to parse visually.

**Comment by mkborregaard** [comment]
can't you use a `bgcolor` tag in each cell?

**Comment by mkborregaard** [comment]
https://www.w3schools.com/tags/att_td_bgcolor.asp

**Comment by SaschaMann** [comment]
That would work.

I was trying to avoid changing `save_html`. That method is also used for other tables so I'd rather not add specific code for supported arguments to it. But I think I'll just do that.

**Comment by SaschaMann** [comment]
grafik

**Comment by mkborregaard** [comment]
That's awesome! I wonder if it should have the horizontal lines as well?

**Comment by SaschaMann** [comment]
Good idea, that looks a lot cleaner!

grafik

**Comment by mkborregaard** [comment]
Great, thanks a lot @SaschaMann !

**Comment by mkborregaard** [comment]
I'm getting a bit of horizontal scrolling on the keyword arguments table (on a macbook pro), which is wider than the others.

**Comment by SaschaMann** [comment]
Ah, I didn't notice, thanks for pointing that out. I'll increase the width a bit.

**Pull request merged**
