### PR TITLE
Only use 90 columns per line in examples

### PR DESCRIPTION
**Pull request by JackDevine**
In some browsers, the lines with a lot of code in the examples actually
get crossed with the table of contents.

Let me know if there are any other formatting bits and pieces that you
would like to change at the same time.

### CODE REVIEW

**Comment by mkborregaard** [comment]
Thanks!

**Comment by daschw** [comment]
Isn't the examples code automatically generated based on the examples in https://github.com/JuliaPlots/Plots.jl/blob/master/src/examples.jl?

**Comment by mkborregaard** [comment]
@ChrisRackauckas I see you merged this - but these md pages used to be auto generated by the "generate_markdown" function in PlotDocs.jl, based on Plots' examples.jl file, and thus all changes in this PR should be overwritten the next time the docs are build. So the 90-char change (which is needed) should be done in Plots.

Did you remove the auto-build capacity when you transferred it to Documenter?

**Comment by mkborregaard** [comment]
Haha @daschw this time you were the fast one.

**Comment by JackDevine** [comment]
Woops, that is my bad... I can go through Plots/src/examples.jl if you like.

**Comment by daschw** [comment]
That would be great!

**Comment by JackDevine** [comment]
Done, I had some weird merge conflicts, but now things are over at
https://github.com/JuliaPlots/Plots.jl/pull/1278/

**Comment by mkborregaard** [comment]
Awesome - @ChrisRackauckas can you just tell us whether the Documenter workflow is still set up to autogenerate this from the examples (I think it still should be, so just checking)

**Comment by ChrisRackauckas** [comment]
that's my bad. I don't think anyone ever deleted it, so it should still be setup to auto-generate. I forgot that was done.

**Comment by mkborregaard** [comment]
The error here is completely that I haven't sat down to figure out how Documenter does things. It was actually not auto-generated in that sense - but when you ran the functions in PlotDocs, it created the markdown files. If Documenter is not set up to run those functions it probably doesn't autoupdate. 
We should have a look at doing that, together with ensuring that Documenter regenerates all figures when it generates the docs (which I also think is not active now).

**Pull request merged**
