### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by daschw**
Rebase of #162 with some GraphRecipes plots.

### CODE REVIEW

**Comment by daschw** [comment]
Ok, finally the build completes for this. Now we have to decide if we want this.

Here's a small summary of changes:
- use Documenter.HTML
- use Documenter at-example blocks to generate images
- add animation examples
- add tutorial to "save gotham" in input_data.md
- remove image files from docs/src/examples

@mkborregaard I remember you saying you were not a big fan of the Documenter HTML theme, but our current mkdocs config does not seem to work anymore: https://travis-ci.org/JuliaPlots/PlotDocs.jl/builds/656300249?utm_source=github_status&utm_medium=notification

Here are a few screenshots of the build of this PR:

plotdocs1

colors

animations

Mostly I'm concerned that the attribute tables have become harder to parse with Documenter's table format:

attributes

supported

I'm still for the changes, though. Are there any objections?

**Comment by daschw** [comment]
I improved the attribute tables now:

attributes

supported

Furthermore this now fixes the LineNumberNode issue in the reference images (https://github.com/JuliaPlots/Plots.jl/issues/2088)

**Comment by mkborregaard** [comment]
Sweet!

**Comment by daschw** [comment]
> @daschw was there anything in particular you'd like me to look at? This is a great reorganization.

No, I just wanted to make sure that there are no objections in general.

**Comment by mkborregaard** [comment]
none :+1: :-)

**Pull request merged**
